---
- name: Variables
  hosts: all
  become: true
  vars:
    my_service: tree
  tasks:
    - name: Install httpd
      package:
        name: "{{my_service}}"
        state: present

    - name: uninstall httpd
      package: 
        name: "{{my_service}}"
        state: absent
# pass --extra-vars my_service="httpd"
#ansible-playbook 8variables.yml --extra-vars my_service="tree"