---
  - name: http services
    hosts:
      - webservers
      - dbservers
    vars:
      service_name: httpd      
    become: true
    tasks:
      - name: install {{ service_name }}
        package: 
          name: "{{ service_name }}"
          state: present
      - name: start {{ service_name }}
        service: 
          name: "{{ service_name }}" 
          state: started
      - name: enable {{ service_name }}
        service: 
          name: "{{ service_name }}"
          state: started
          enabled: true
      - name: restart {{ service_name }}
        service:
          name: "{{ service_name }}"
          state: restarted
      - name: copy  
        copy:
         src: ./file1
         dest: /etc/test.html