---
  - name: http services
    hosts:
      - webservers
      - dbservers
    vars:
      service_name: httpd
    become: true
    tasks:
      - name: install {{ service_name }}
        package: 
          name: "{{ service_name }}"
          state: present
        tags:
          - install
          - common
        notify:
          - start server
      - name: stop server
        service: 
          name: "{{ service_name }}" 
          state: stopped
        tags:
          - stop
          - common
        notify:
          - start server
      - name: copy
        copy:
         src: ./file1
         dest: /var/www/html/index.html
        tags:
          - copy
          - common
        notify : 
          - restart {{ service_name }}
      - name: enable {{ service_name }}
        service: 
          name: "{{ service_name }}"
         # state: started
          enabled: true

    handlers:
      - name: start server
        service: 
          name: "{{ service_name }}" 
          state: started

      - name: restart {{ service_name }}
        service:
          name: "{{ service_name }}"
          state: restarted
      

# ---
# - name: httpd with tags and handlers
#   hosts: all
#   become: true
#   tasks:
#     - name: install httpd
#       package:
#         name: httpd
#         state: present
#       notify:
#         - start service
#     - name: copy file
#       copy:
#         src: index.html
#         dest: ./fm/masterdir
#       notify: 
#         - restart service
#   handlers:
#     - name: start service
#       service:
#         - name: httpd
#           state: started
#     - name: restart service
#       service:
#         name: httpd
#         state: restarted
